spring:
  application:
    name: notification-processor
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      enable-auto-commit: false
server:
  port: 8766
logging:
  level:
    org.apache.kafka.clients.consumer.KafkaConsumer: DEBUG
    org.apache.kafka.clients.consumer.internals.ConsumerCoordinator: DEBUG
    org.apache.kafka.clients.consumer.internals.Fetcher: DEBUG
    org.apache.kafka.clients.consumer.internals.SubscriptionState: DEBUG